// Auto generated by scripts/buildschema.go -- Do not edit
package leif

var schemas = map[string]string{
	"0.1.0": `{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Sherpa Definition",
    "type": "object",
    
    "definitions": {
        "route": {
            "properties": {
                "methods": { "$ref": "#/definitions/methods" },
                "host": { "type": "string" },
                "schemes": { "type": "string" },
                "headers": { "type": "array" },
                "queries": { "type": "array" },
                "function": { "type": "string" },
                "middlewares": { "$ref": "#/definitions/middlewares" },
                "package": { "type": "string" }
            },
            "patternProperties": {
                "^/.+$": { "$ref": "#/definitions/route" }
            }
        },

        "methods": {
            "type": "array",
            "minItems": 1,
            "items": { 
                "type": "string", 
                "enum": [ 
                    "GET", 
                    "HEAD",
                    "POST",
                    "PUT", 
                    "DELETE", 
                    "PATCH",
                    "CONNECT",
                    "OPTIONS",
                    "TRACE"
                ]
            },
            "uniqueItems": true
        },

        "middlewares": {
            "properties": {
                "functions": {
                    "type": "array",
                    "minItems": 1,
                    "items": { "type": "string" }
                },
                "package": { "type": "string" },
                "exclude": { 
                    "type": "array",
                    "minItems": 1,
                    "items": { "type": "string" }
                }
            },
            "required": [ "functions" ],
            "additionalProperties": false
        }
    },

    "properties": {
        "middlewares": {
            "patternProperties": {
                "^.+$": { 
                    "$ref": "#/definitions/middlewares"
                }
            }
        },
        "routes": {
            "properties": {
                "/": { "$ref": "#/definitions/route" }
            },
            "required": ["/"],
            "additionalProperties": false
        }
    },
    "additionalProperties": false,
    "required": ["routes"]
}
`,
}
