package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strings"
)

func main() {
	fs, _ := ioutil.ReadDir("./schemas")
	out, _ := os.Create("schemas.go")

	// Write package
	out.Write([]byte("// Auto generated by scripts/buildschema.go -- Do not edit\n"))
	out.Write([]byte("package leif\n\nvar schemas = map[string]string {\n"))

	for _, f := range fs {
		name := strings.TrimSuffix(f.Name(), ".json")
		out.Write([]byte("\t\"" + name + "\"" + ": `"))

		f, err := os.Open("./schemas/" + f.Name())

		if err != nil {
			fmt.Println(err)
		}
		io.Copy(out, f)
		out.Write([]byte("`,\n"))
	}
	out.Write([]byte("}\n"))
}
